### ISSUE TITLE
[Feature] Disable SBA features added by other mods

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Kuschel-Swein/smixer-mod#1]
### Feature Description

This might be a good idea since it means less work having to patch these if Skyblock updates and gets people to use better alternatives for some of these features.

A list of the main features other mods replace are here, feel free to do all or none idk up to you

- [ ] #2
- [ ] #3
- [ ] #4
- [ ] #5

Others can be found [here](https://microcontrollersdev.github.io/Alternatives/1.8.9/skyblockaddons) if you want to do all of them. I only put the ones above that have alternatives that are undeniably superior to SBA's version of them.

**Comment by Kuschel-Swein** [comment]
Hey,
ich denke das ist eine wirklich gute Idee.
Jedoch würde ich nicht alle Funktionen die es auch in anderen Mods gibt deaktivieren wollen, da dann nichts mehr übrig bleiben würde.

**Comment by MicrocontrollersDev** [comment]
> Hey, ich denke das ist eine wirklich gute Idee. Jedoch würde ich nicht alle Funktionen die es auch in anderen Mods gibt deaktivieren wollen, da dann nichts mehr übrig bleiben würde.

💀

**Comment by Kuschel-Swein** [comment]
Ups, I forgot that this is an english repo.
